language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
script:
  - bundle exec rspec
notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 1.9
    - rvm: 2.2
    - rvm: ruby-head
